# ------------------------------------------------------------------------------
# Copyright 2012-2021 Aerospike, Inc.
#
# Portions may be licensed to Aerospike, Inc. under one or more contributor
# license agreements.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
# ------------------------------------------------------------------------------

{{- if .Values.enableAerospikeMonitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  labels:
    app: {{ template "aerospike.name" . }}-alertmanager
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
data:
  # default alertmanager configuration file
  {{ if .Files.Get "files/alertmanager.yaml" }}
  alertmanager.yaml: {{ tpl (.Files.Get "files/alertmanager.yaml") . | quote }}
  {{ end }}

  {{- if and .Values.alertmanager.alertmanagerConfFilePath .Values.alertmanager.alertmanagerConfFile }}
  {{ fail "Both legacy(alertmanager.alertmanagerConfFilePath) and new(alertmanager.alertmanagerConfFile) are configured! Use only one!" }}
  {{- end }}

  {{- if and (or .Values.alertmanager.alertmanagerConfFilePath .Values.alertmanager.alertmanagerConfFile) (.Values.alertmanager.alertmanagerConfFileBase64) }}
  {{ fail "Both alertmanager.alertmanagerConfFilePath/alertmanager.alertmanagerConfFile and alertmanager.alertmanagerConfFileBase64 are configured! Use only one!" }}
  {{- end }}

  # old config for alertmanager configuration file
  {{ if (.Values.alertmanager.alertmanagerConfFilePath) }}
  alertmanager.yaml: |-
    {{ .Values.alertmanager.alertmanagerConfFilePath | nindent 4 | trim }}
  {{ end }}

  # new config for alertmanager configuration file
  {{ if (.Values.alertmanager.alertmanagerConfFile) }}
  alertmanager.yaml: |-
    {{ .Values.alertmanager.alertmanagerConfFile | nindent 4 | trim }}
  {{ end }}

  # alertmanager configuration file provided as base64 encoded string
  {{ if (.Values.alertmanager.alertmanagerConfFileBase64) }}
  alertmanager.yaml: |-
    {{ .Values.alertmanager.alertmanagerConfFileBase64 | b64dec | nindent 4 | trim }}
  {{ end }}
{{- end }}
