# ------------------------------------------------------------------------------
# Copyright 2012-2021 Aerospike, Inc.
#
# Portions may be licensed to Aerospike, Inc. under one or more contributor
# license agreements.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
# ------------------------------------------------------------------------------

{{- if and .Values.enableExternalIpServices .Values.externalIPServices.enabled }}
{{ fail "Both legacy(enableExternalIpServices) and new(externalIPServices) are enabled! Use only one!" }}
{{- end }}

{{- if .Values.enableExternalIpServices }}
{{ $length := 0 }}
{{- if .Values.externalIpEndpoints }}
{{ $length = len .Values.externalIpEndpoints }}
{{- end }}
{{ if lt $length (int .Values.dbReplicas) }}
{{ fail "Number of externalIpEndpoints should be equal to or more than dbReplicas" }}
{{ end }}
{{- $dot := . }}
{{ range $podIndex := until (int .Values.dbReplicas) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "extip-{{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $podIndex }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "aerospike.name" $dot }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
spec:
  externalIPs:
    - {{ $ip := index $.Values.externalIpEndpoints $podIndex }} {{ $ip.IP }}
  ports:
    - port: {{ $ip := index $.Values.externalIpEndpoints $podIndex }} {{ $ip.Port }}
      targetPort: {{ $.Values.aerospikeClientPort | default 3000 }}
      protocol: TCP
      name: aerospike-plain
  selector:
    statefulset.kubernetes.io/pod-name: "{{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $podIndex }}"
{{ end -}}
{{- end }}

{{- if .Values.externalIPServices.enabled }}
{{ $length := len .Values.externalIPServices.externalIPEndpoints }} {{ if lt $length (int .Values.dbReplicas) }}
{{ fail "Number of externalIPServices.externalIPEndpoints should be equal to or more than dbReplicas" }}
{{ end }}
{{- $dot := . }}
{{ range $podIndex := until (int .Values.dbReplicas) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "extip-{{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $podIndex }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "aerospike.name" $dot }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    {{- with $.Values.externalIPServices.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with $.Values.externalIPServices.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  externalIPs:
    - {{ $ip := index $.Values.externalIPServices.externalIPEndpoints $podIndex }} {{ $ip.IP }}
  ports:
    - port: {{ $ip := index $.Values.externalIPServices.externalIPEndpoints $podIndex }} {{ $ip.Port }}
      targetPort: {{ $.Values.aerospikeClientPort | default 3000 }}
      protocol: TCP
      name: aerospike-plain
  selector:
    statefulset.kubernetes.io/pod-name: "{{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $podIndex }}"
{{ end -}}
{{- end }}
---
